eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
    #  defaultZone: http://localhost:8761/eureka/
      defaultZone: http://serviceregistry:8761/eureka/
    instance:
      hostname: serviceregistry
